### PR TITLE
Gradle and dependency updates

### PR DESCRIPTION
**Pull request by friederbluemle**

### CODE REVIEW

**Comment by friederbluemle** [comment]
Hmm, did you somehow squash and force push to master? a57e18c cannot be found on `master`, even though it says

    fcannizzaro merged commit a57e18c into fcannizzaro:master 6 hours ago

I had to hard reset my branch, and force delete my local `update-project`. In the future, it would be good to follow Git best practices and never delete public history. :+1:

**Comment by friederbluemle** [comment]
Also, I noticed some of the commits just disappeared. For instance, the `gradlew` executable bit is not set anymore. I cherry-picked some of the commits and opened another PR: #15 Please check.

**Comment by fcannizzaro** [comment]
Project building failed on jitpack after #14 and I forgot to update code in these weeks. Build success now.

**Comment by friederbluemle** [comment]
Thanks :+1:

**Pull request merged**
